### ISSUE TITLE
BUG: Hide Decimal option strips out more than it should.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-level-cost-text#18] opened 2021-07-27 10:10 UTC
There is a minor issue when hiding unnecessary decimals strips out more than just the decimals and removes a `</strong> ` tag in the process as well.

**Steps to recreate**

1. Leave the level's custom level cost text setting blank.
2. Navigate to advanced settings, set the "Hide Unnecessary Decimals" to "Yes"
3. View your checkout page, everything after cost text is bold. 

On a side note, the browser inspection tool shows the correct code, but if you view the full page source and search for the cost text you will see it's missing a `</strong>` tag by the pricing.

**Screenshots**

_**Before**_
![before-hide-decimals](https://user-images.githubusercontent.com/12629136/127136566-2aecf586-00cf-454b-9a40-cfe68a5c5b85.png)

_**After Setting Enabled**_
![after-hide-decimals](https://user-images.githubusercontent.com/12629136/127136826-3ea56d1b-66ae-4b05-9abe-49e32bb9d7fd.png)

**Comment by andrewlimaza** [comment] 2021-07-27 10:11
Related code: https://github.com/strangerstudios/pmpro-level-cost-text/blob/master/pmpro-level-cost-text.php#L92-L105

**Comment by mircobabini** [comment] 2022-03-31 13:53
Duplicate of #13

**Closed** 2023-01-11 14:54 UTC
